const CFG={base:'https://www.okx.com',instId:'BTC-USDT-SWAP',equity0:10000,pool0:3000,riskPct:.015,dailyLossPct:.03,maxLeverage:10,feeRate:.0005,pollMs:5000};
const S={equity:CFG.equity0,pool:CFG.pool0,pnl:0,running:false,price:null,mark:null,oi:null,prevOi:null,funding:null,ratio:null,volume:null,bookImbalance:null,taker:null,candles:{},signal:'等待真实数据',score:null,position:null,entry:null,stop:null,target:null,lossStreak:0,dayStart:CFG.equity0,logs:[],lastData:0,alerts:[]};
const $=id=>document.getElementById(id); const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'--';
function log(x){S.logs.unshift(new Date().toLocaleTimeString()+'  '+x);S.logs=S.logs.slice(0,40);$('log').textContent=S.logs.join('\n');}
function pct(x,d=3){return Number.isFinite(x)?(x*100).toFixed(d)+'%':'--'}
function set(id,v){$(id).textContent=v}
function render(){set('equity',fmt(S.equity));set('pool',fmt(S.pool));set('pnl',fmt(S.pnl));set('price',S.price?fmt(S.price):'--');set('oi',S.oi?fmt(S.oi,2):'--');set('funding',S.funding!=null?pct(S.funding,4):'--');set('ratio',S.ratio!=null?S.ratio.toFixed(3):'--');set('volume',S.volume?fmt(S.volume,2):'--');set('position',S.position?`${S.position==='long'?'多':'空'} @ ${fmt(S.entry)}`:'空仓');set('signal',S.signal);set('score',S.score==null?'--':S.score);set('oidelta',S.prevOi&&S.oi?((S.oi/S.prevOi-1)*100).toFixed(2)+'%':'--');set('imbalance',S.bookImbalance!=null?(S.bookImbalance*100).toFixed(1)+'%':'--');set('taker',S.taker!=null?(S.taker*100).toFixed(1)+'%买方':'--');$('alerts').textContent=S.alerts.length?S.alerts.slice(0,5).join(' | '):'暂无异常事件';}
async function api(path){const r=await fetch(CFG.base+path,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();if(j.code!=='0')throw Error(j.msg||'API error');return j.data}
function parseCandle(a){return a.slice().reverse().map(x=>({ts:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],vol:+x[5]}))}
async function loadCandles(bar){const d=await api(`/api/v5/market/candles?instId=${CFG.instId}&bar=${bar}&limit=100`);S.candles[bar]=parseCandle(d);}
function ema(a,n){const k=2/(n+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(l===0)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
function macd(a){if(a.length<35)return null;const fast=ema(a,12),slow=ema(a,26);return fast-slow}
function bb(a,n=20){if(a.length<n)return null;const x=a.slice(-n),m=x.reduce((s,v)=>s+v,0)/n,sd=Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/n);return {m,up:m+2*sd,lo:m-2*sd}}
function tf(bar){const c=S.candles[bar]||[];if(c.length<30)return {trend:'数据不足'};const a=c.map(x=>x.c),last=a.at(-1),e20=ema(a,20),e50=ema(a,50),R=rsi(a),M=macd(a),B=bb(a);let score=(last>e20?1:-1)+(e20>e50?1:-1)+(R>55?1:R<45?-1:0)+(M>0?1:-1);return {trend:score>=2?'偏多':score<=-2?'偏空':'震荡',score,last,e20,e50,R,M,B}}
function analyse(){const t15=tf('15m'),t30=tf('30m'),t60=tf('1H');set('tf15',t15.trend);set('tf30',t30.trend);set('tf60',t60.trend);const t=t15.last?t15:t30;set('ema',t.e20?fmt(t.e20):'--');set('rsi',t.R? t.R.toFixed(1):'--');set('macd',t.M!=null?fmt(t.M,2):'--');if(t.B&&t.last){const pos=(t.last-t.B.lo)/(t.B.up-t.B.lo);set('bb',(pos*100).toFixed(1)+'%');}else set('bb','--');let score=0;const parts=[];[t15,t30,t60].forEach((x,i)=>{if(x.score){score+=x.score*(i===2?2:i===1?1.5:1);parts.push(`${['15m','30m','1h'][i]}${x.trend}`)}});if(S.oi&&S.prevOi){const od=S.oi/S.prevOi-1;if(S.price&&S._prevPrice){const pd=S.price/S._prevPrice-1;if(pd>0&&od>0){score+=1.5;parts.push('价升OI升')}if(pd<0&&od>0){score-=1.5;parts.push('价跌OI升')}if(pd>0&&od<0){score-=.5;parts.push('价升OI降')}if(pd<0&&od<0){score+=.5;parts.push('价跌OI降')}}}if(S.funding!=null){if(S.funding>0.0002){score-=.8;parts.push('正资金费率')}else if(S.funding<-0.0002){score+=.8;parts.push('负资金费率')}}if(S.ratio!=null){if(S.ratio>1.05){score+=.7;parts.push('多空比偏多')}else if(S.ratio<.95){score-=.7;parts.push('多空比偏空')}}if(S.bookImbalance!=null){score+=S.bookImbalance*1.2;parts.push('盘口真实失衡')}if(S.taker!=null){score+=(S.taker-.5)*3;parts.push('主动成交真实数据')}score=Math.max(-10,Math.min(10,score));S.score=Math.round(score*10);S.signal=S.score>=35?'偏多':S.score<=-35?'偏空':'观望';$('reason').textContent=parts.length?parts.join(' · '):'等待更多真实数据形成交叉确认';render();return {t15,t30,t60}}
function riskAllows(){const daily=Math.max(0,CFG.equity0-S.equity);return daily<=CFG.equity0*CFG.dailyLossPct&&S.lossStreak<3}
function simulate(){if(!S.running||!S.price||!riskAllows())return;if(S.position){const dir=S.position==='long'?1:-1;const ret=(S.price-S.entry)/S.entry*dir; if(ret<=-0.006||ret>=0.012){const notional=S.pool*CFG.maxLeverage*.3;const gross=notional*ret;const fee=notional*CFG.feeRate*2;const pnl=gross-fee;S.equity+=pnl;S.pool+=pnl;S.pnl+=pnl;S.lossStreak=pnl<0?S.lossStreak+1:0;log(`模拟平${S.position==='long'?'多':'空'} @ ${fmt(S.price)}，本次 ${pnl>=0?'+':''}$${fmt(pnl)}`);S.position=null;S.entry=null;}}
if(!S.position&&S.score!=null&&Math.abs(S.score)>=45&&riskAllows()){S.position=S.score>0?'long':'short';S.entry=S.price;log(`模拟开${S.position==='long'?'多':'空'} @ ${fmt(S.entry)}，信号 ${S.score}`)}render()}
async function refresh(){try{const [tick,oi,fund,books]=await Promise.all([api(`/api/v5/market/ticker?instId=${CFG.instId}`),api(`/api/v5/public/open-interest?instType=SWAP&instId=${CFG.instId}`),api(`/api/v5/public/funding-rate?instId=${CFG.instId}`),api(`/api/v5/market/books?instId=${CFG.instId}&sz=20`)]);S._prevPrice=S.price;S.price=+tick[0].last;S.mark=+tick[0].markPx;S.volume=+tick[0].vol24h;S.prevOi=S.oi;S.oi=+oi[0].oi;S.funding=+fund[0].fundingRate;const b=books[0];const bid=b.bids.reduce((s,x)=>s+(+x[0])*(+x[1]),0),ask=b.asks.reduce((s,x)=>s+(+x[0])*(+x[1]),0);S.bookImbalance=(bid-ask)/(bid+ask||1);S.lastData=Date.now();S.alerts=[];if(S._prevPrice){const p=(S.price/S._prevPrice-1)*100;if(Math.abs(p)>=0.6)S.alerts.push(`⚠️ 5秒价格变化 ${p.toFixed(2)}%`) }if(S.prevOi){const o=(S.oi/S.prevOi-1)*100;if(Math.abs(o)>=0.5)S.alerts.push(`⚠️ OI变化 ${o.toFixed(2)}%`) }await Promise.all(['15m','30m','1H'].map(loadCandles));
// Long/short ratio is public Rubik data; if unavailable, keep it unavailable rather than fabricate it.
try{const ls=await api(`/api/v5/rubik/stat/contracts/long-short-account-ratio?ccy=BTC&period=5m`);if(ls&&ls[0])S.ratio=+ls[0][1]||+ls[0].ratio||null;}catch(e){S.ratio=null}
try{const tv=await api(`/api/v5/rubik/stat/taker-volume?ccy=BTC&instType=CONTRACTS&period=5m`);if(tv&&tv[0]){const buy=+tv[0][1],sell=+tv[0][2];S.taker=buy/(buy+sell||1)}}catch(e){S.taker=null}
analyse();$('dataStatus').textContent='已连接：OKX 真实公共行情 · '+new Date().toLocaleTimeString();}catch(e){$('dataStatus').textContent='真实数据连接失败：'+e.message+'（未使用任何随机数据）';S.alerts=['❌ 真实数据暂时不可用，请稍后重试'];render();}}
$('start').onclick=()=>{if(S.running)return;S.running=true;$('status').textContent='当前：V3 自动模拟运行中；行情全部来自真实 OKX 公共数据。';log('启动 V3：真实行情 + 模拟撮合。不会发送真实订单。');refresh();S.timer=setInterval(()=>{refresh();simulate()},CFG.pollMs)};
$('stop').onclick=()=>{S.running=false;clearInterval(S.timer);$('status').textContent='当前：已停止';log('停止自动模拟。')};
$('reset').onclick=()=>{S.equity=CFG.equity0;S.pool=CFG.pool0;S.pnl=0;S.lossStreak=0;S.position=null;S.entry=null;S.logs=[];log('模拟账户重置：$10,000 / 策略池 $3,000');render()};
render();refresh();
